### ISSUE TITLE
feature: 解析github头像

### ISSUE THREAD

**Issue by chuwt** [yuzhouu/ordinary-days#8]
添加解析github头像的逻辑，如果有头像图片，可以使用自定义图片，默认是解析github头像

**Comment by yuzhouu** [comment]
解析头像是指通过github username 自动生成头像，还是指用户输入头像url？

**Comment by chuwt** [comment]
通过这个链接可以获取到github用户头像，然后显示 `https://avatars.githubusercontent.com/chuwt`
